config/routes.rb
Rails.application.routes.draw do
  resources :bowling_centers do
    resources :scores
  end
  
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  resources :users, only: [:show]
  root to:  'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bowling_center.rb
class BowlingCenter < ApplicationRecord
  has_many :scores

  validates :name, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  belongs_to :bowling_center

  validates :point, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :scores
  has_one_attached :image

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :favorite_ball, %i(image)])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :favorite_ball, %i(image)])
  end
end

app/controllers/bowling_centers_controller.rb
class BowlingCentersController < ApplicationController
  before_action :set_bowling_center, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @bowling_centers = BowlingCenter.all
  end

  def show
    @bowling_center = BowlingCenter.find(params[:id])
    @score = Score.where(user_id: current_user.id, bowling_center_id: params[:bowling_center_id])
  end

  def new
    @bowling_center = BowlingCenter.new
  end

  def edit
    @bowling_center = BowlingCenter.find(params[:id])
  end

  def create
    @bowling_center = BowlingCenter.new(bowling_center_params)

    respond_to do |format|
      if @bowling_center.save
        format.html { redirect_to bowling_center_path(@bowling_center), notice: "ボウリング場を登録しました" }
        format.json { render :show, status: :created, location: @bowling_center }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bowling_center.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bowling_center.update(bowling_center_params)
        format.html { redirect_to bowling_center_path(@bowling_center), notice: "ボウリング場を編集しました" }
        format.json { render :show, status: :ok, location: @bowling_center }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bowling_center.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bowling_center.destroy

    respond_to do |format|
      format.html { redirect_to bowling_centers_path, notice: "ボウリング場を削除しました" }
      format.json { head :no_content }
    end
  end

  private
    def set_bowling_center
      @bowling_center = BowlingCenter.find(params[:id])
    end

    def bowling_center_params
      params.require(:bowling_center).permit(:name, :address, :phone_number, :hp)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @score = Score.where(user_id: current_user.id, bowling_center_id: params[:bowling_center_id])
    @bowling_center = BowlingCenter.find(params[:bowling_center_id])
  end

  def show
    @bowling_center = BowlingCenter.find(params[:bowling_center_id])
    @score = Score.where(user_id: current_user.id, bowling_center_id: params[:bowling_center_id])
  end

  def new
    @bowling_center = BowlingCenter.find(params[:bowling_center_id])
    @score = Score.new
  end

  def edit
    @bowling_center = BowlingCenter.find(params[:bowling_center_id])
    @score = Score.find(params[:id])
  end

  def create
    @score = Score.new(score_params)
    @bowling_center = BowlingCenter.find(params[:bowling_center_id])
    @score.bowling_center_id = @bowling_center.id
    @score.user_id = current_user.id

    respond_to do |format|
      if @score.save!
        format.html { redirect_to bowling_center_scores_path(@bowling_center), notice: "スコアを登録しました" }
        format.json { render :index, status: :created, location: @score }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @bowling_center = BowlingCenter.find(params[:bowling_center_id])
    @score.bowling_center_id = @bowling_center.id
    @score.user_id = current_user.id
    
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to bowling_center_scores_path(@bowling_center, @score), notice: "スコアを編集しました" }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @score.destroy

    respond_to do |format|
      format.html { redirect_to bowling_center_scores_path, notice: "スコアを削除しました" }
      format.json { head :no_content }
    end
  end

  private
    def set_score
      @score = Score.find(params[:id])
    end

    def score_params
      params.require(:score).permit(:point)
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: :destroy

  def ensure_normal_user
    redirect_to root_path, alert: 'ゲストユーザーは削除できません。' if resource.email == 'guest@example.com'
  end

  protected

  def after_sign_up_path_for(resource)
    root_path
  end

  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bowling_centers_helper.rb
module BowlingCentersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bowling_centers/_form.html.erb
<div class="text-center">
  <%= form_with(model: bowling_center) do |form| %>
    <% if bowling_center.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(bowling_center.errors.count, "error") %> prohibited this bowling_center from being saved:</h2>

        <ul>
          <% bowling_center.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <table id="form">
      <tr>
        <th><i style="color:red;">(必須)</i><%= form.label :name , "ボウリング場名" %></th>
        <td><%= form.text_field :name, id:"bowling_center_name" %></td>
      </tr>
      <tr>
        <th><i style="color:red;">(必須)</i><%= form.label :address , "住所" %></th>
        <td><%= form.text_field :address, id:"bowling_center_address" %></td>
      </tr>
      <tr>
        <th><%= form.label :phone_number , "電話番号" %></th>
        <td><%= form.text_field :phone_number, id:"bowling_center_number" %></td>
      </tr>
      <tr>
        <th><%= form.label :hp , "ホームページ" %></th>
        <td><%= form.text_field :hp, id:"bowling_center_hp" %></td>
      </tr>
    </table>

    <div class="actions mt-3">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/bowling_centers/edit.html.erb
<div class="container justify-content-center">
  <%= render 'form', bowling_center: @bowling_center %>
  <div class="d-flex justify-content-center">
    <%= link_to 'ボウリング場詳細に戻る', @bowling_center, class:"btn btn-outline-primary m-3" %>
    <%= link_to 'ボウリング場一覧', bowling_centers_path, class:"btn btn-outline-primary m-3" %>
    <%= link_to 'トップに戻る', root_path, class:"btn btn-outline-dark m-3" %>
  </div>
</div>

app/views/bowling_centers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container justify-content-center">
  <h1 class="text-center mb-3">ボウリング場一覧</h1>
  <table id="form" class="table">
    <thead>
      <tr>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @bowling_centers.each do |bowling_center| %>
        <tr>
          <td class="h3"><%= link_to bowling_center.name, bowling_center, class:"text-decoration-none", id:"bowling_center_name" %></td>
          <td class="h5"><%= link_to '削除', bowling_center, method: :delete, data: { confirm: '本当に削除しますか？' }, class:"text-decoration-none" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center mt-3">
    <%= link_to 'ボウリング場を登録する', new_bowling_center_path, class:"btn btn-primary m-3 text-white", id:"new_bowling_center" %>
    <%= link_to 'トップに戻る', root_path, class:"btn btn-outline-dark m-3", id:"root" %>
  </div>
</div>

app/views/bowling_centers/new.html.erb
<div class="container justify-content-center">
  <h1 class="text-center mb-3">ボウリング場を登録する</h1>
  <%= render 'form', bowling_center: @bowling_center %>
  <div class="d-flex justify-content-center">
    <%= link_to 'ボウリング場一覧', bowling_centers_path, class:"btn btn-outline-primary m-3", id:"bowling_centers" %>
    <%= link_to 'トップに戻る', root_path, class:"btn btn-outline-dark m-3", id:"root" %>
  </div>
</div>

app/views/bowling_centers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>ボウリング場名</th>
            <th>住所</th>
            <th>電話番号</th>
            <th>ホームページ</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td><%= @bowling_center.name %></td>
              <td><%= @bowling_center.address %></td>
              <td><%= @bowling_center.phone_number %></td>
              <td><%= @bowling_center.hp %></td>
              <td><%= link_to '編集', [:edit, :bowling_center], class:"text-decoration-none" %></td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div id="map" class="justify-content-center"></div>
  <div class="d-flex justify-content-center mt-3">
    <%= link_to "スコアを入力する", new_bowling_center_score_path(@bowling_center), class:"btn btn-danger m-3" %>
    <%= link_to "スコア一覧を見る", bowling_center_scores_path(@bowling_center), class:"btn btn-outline-danger btn-ignore m-3" %>
  </div>
  <div class="d-flex justify-content-center mt-1">
    <%= link_to 'ボウリング場一覧に戻る', bowling_centers_path, class:"btn btn-outline-primary m-3" %>
    <%= link_to 'トップに戻る', root_path, class:"btn btn-outline-dark m-3" %>
  </div>
</div>

<script type="text/javascript">
  function initMap() {
    var test = {lat: <%= @bowling_center.latitude %>, lng: <%= @bowling_center.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 15, 
              center: test
              });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);
    var contentString = '住所：<%= @bowling_center.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });
    var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                });
    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }
  window.onload = function () {
      initMap();
  }
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap">
</script>

app/views/home/top.html.erb
<div class="container w-100">
  <div class="back-img">
    <% if current_user %>
      <div class="d-flex justify-content-center bg-white">
        <%= link_to "ボウリング場を登録する", new_bowling_center_path, class:"btn btn-primary btn-lg w-100 h-100 m-3 text-white" %>
        <%= link_to "ボウリング場一覧", bowling_centers_path, class:"btn btn-outline-primary btn-lg w-100 h-100 m-3"%>
      </div>
    <% else %>
    <div class="bg-white">
      <div class="justify-content-center bg-white">
        <p class="h4 text-center">Scorer for Bowlersへようこそ！</p>
        <p class="h4 text-center">Scorer for Bowlersはお気に入りのボウリング場毎に</p>
        <p class="h4 text-center">スコアを管理することができるアプリケーションです！</p>
        <p class="h4 text-center">ご利用にはログインがご必要となります！</p>
      </div>
      <div class="d-flex mt-5 bg-white">
        <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary me-3 text-decoration-none text-white btn-lg w-100 h-100 m-3" %>
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-secondary me-3 text-decoration-none text-white btn-lg w-100 h-100 m-3" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scorer for Bowlers</title>
    <%= favicon_link_tag('icons8-ボウリング-64.png') %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>
  <body>
    <div class="footerFixed">
      <header class="p-1 m-2 fs-5">
        <div>
          <% if current_user %>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <div class="container-fluid">
                <%= link_to "Scorer for Bowlers", root_path, class:"text-decoration-none mt-1 ms-5 fs-1", id:"logo" %>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                  <ul class="navbar-nav">
                    <li class="nav-item">
                      <%= link_to "プロフィール", user_path(current_user), class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
                    </li>
                  </ul>
                </div>
              </div>
            </nav>
          <% else %>
            <%= link_to "Scorer for Bowlers", root_path, class:"text-decoration-none mt-1 ms-5 fs-1" ,id:"logo" %>
            <div class="d-flex justify-content-end">
              <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: "btn btn-primary me-3 text-decoration-none text-white" %>
              <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary me-3 text-decoration-none text-white" %>
              <%= link_to "新規登録", new_user_registration_path, class: "btn btn-secondary me-3 text-decoration-none text-white" %>
            </div>
          <% end %>
        </div>
      </header>
      <p class="alert"><%= alert %></p>
        <%= yield %>
      <footer class="bg-dark text-center text-light p-5 mt-5"">
        (c) ybowlproject
      </footer>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </div>
  </body>
</html>

app/views/scores/_form.html.erb
<div class="text-center">
  <%= form_with(model: [@bowling_center, @score]) do |form| %>
    <% if score.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

        <ul>
          <% score.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <table id="form">
      <tr>
        <th><%= form.label :point , "点数"%>(半角)</th>
        <td><%= form.number_field :point, min:0, max:300, id:"point" %></td>
      </tr>
    </table>

      <%= hidden_field_tag :id, @bowling_center.id %>
      <%= hidden_field_tag :name, @bowling_center.name %>

    <div class="actions mt-3">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/scores/edit.html.erb
<div class="container justify-content-center">
  <h1 class="text-center mb-3">スコア編集</h1>
  <%= render 'form', score: @score %>
  <div class="d-flex justify-content-center">
    <%= link_to "スコア一覧を見る", bowling_center_scores_path(@bowling_center, @score), class:"btn btn-outline-danger m-3" %>
    <%= link_to 'ボウリング場詳細に戻る', @bowling_center, class:"btn btn-outline-primary m-3" %>
    <%= link_to 'ボウリング場一覧', bowling_centers_path, class:"btn btn-outline-primary m-3" %>
    <%= link_to 'トップに戻る', root_path, class:"btn btn-outline-dark m-3" %>
  </div>
</div>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>ゲーム数</th>
            <th>投球日時</th>
            <th>点数</th>
          </tr>
        </thead>
        <tbody>
          <% @score.each.with_index(1) do |score, index| %>
            <tr>
              <td><%= index %></td>
              <td><%= score.created_at.strftime("%Y年%m月%d日 %H時%M分") %></td>
              <td><%= score.point %></td>
              <td><%= link_to '編集', edit_bowling_center_score_path(id: score), class:"text-decoration-none" %></td>
              <td><%= link_to '削除', "/bowling_centers/#{@bowling_center.id}/scores/#{score.id}", method: :delete, data: { confirm: '本当に削除しますか？' }, class:"text-decoration-none" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col">
      <table class="table">
        <tr>
          <th>MAX</th>
          <td>
          <% if @score.any? %>
            <%= @score.maximum('point') %>点
          <% else %>
            0点
          <% end %>
          </td>
        </tr>
        <tr>
          <th>AVE</th>
          <td>
          <% if @score.any? %>
            <%= @score.average('point').floor %>点
          <% else %>
            0点
          <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "スコアを入力する", new_bowling_center_score_path(@bowling_center), class:"btn btn-danger m-3 text-white" %>
    <%= link_to 'ボウリング場詳細に戻る', @bowling_center, class:"btn btn-outline-primary m-3" %>
    <%= link_to 'ボウリング場一覧', bowling_centers_path, class:"btn btn-outline-primary m-3" %>
    <%= link_to 'トップに戻る', root_path, class:"btn btn-outline-dark m-3" %>
  </div>
</div>

app/views/scores/new.html.erb
<div class="container justify-content-center">
  <h1 class="text-center mb-3">スコア入力</h1>
  <%= render 'form', score: @score %>
  <div class="d-flex justify-content-center">
    <%= link_to 'ボウリング場詳細に戻る', @bowling_center, class:"btn btn-outline-primary m-3" %>
    <%= link_to 'ボウリング場一覧', bowling_centers_path, class:"btn btn-outline-primary m-3" %>
    <%= link_to 'トップに戻る', root_path, class:"btn btn-outline-dark m-3" %>
  </div>
</div>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>
<div class="containar">
  <div class="row">
    <div class="col">
      <table class="table">
        <thead>
          <tr>
            <th>ゲーム数</th>
            <th>投球日時</th>
            <th>点数</th>
          </tr>
        </thead>
        <tbody>
          <% @score.each.with_index(1) do |score, index| %>
            <tr>
              <td><%= index %></td>
              <td><%= score.created_at.strftime("%Y年%m月%d日 %H時%M分") %></td>
              <td><%= score.point %></td>
              <td><%= link_to '編集', edit_bowling_center_score_path(id: score) %></td>
              <td><%= link_to '削除', "/bowling_centers/#{@bowling_center.id}/scores/#{score.id}", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col">
      <table class="table">
        <tr>
          <th>MAX</th>
          <td><%= @score.maximum('point') %>点</td>
        </tr>
        <tr>
          <th>AVE</th>
          <td><%= @score.average('point').floor %>点</td>
        </tr>
      </table>
    </div>
  </div>
  <div class="d-flex justify-content-center">
    <button type="button" class="btn btn-danger m-3"><%= link_to "スコアを入力する", new_bowling_center_score_path(@bowling_center) %></button>
    <button type="button" class="btn btn-outline-primary m-3"><%= link_to 'ボウリング場詳細に戻る', @bowling_center %></button>
    <button type="button" class="btn btn-outline-primary m-3"><%= link_to 'ボウリング場一覧', bowling_centers_path %></button>
    <button type="button" class="btn btn-outline-dark m-3"><%= link_to 'トップに戻る', root_path %></button>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "パスワードをお忘れの方はこちら", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container justify-content-center">
  <h1 class="text-center">プロフィール</h1>

  <div class="text-center">
    <% if @user.image.attached? %>
      <%= image_tag @user.image, class:"text-center user-icon" %>
    <% end %>
  </div>
  <br>
  <p class="text-center">アカウント名：<%= @user.name %></p>
  <p class="text-center">メールアドレス：<%= @user.email %></p>
  <p class="text-center">お気に入りのボール：<%= @user.favorite_ball %></p>

  <div class="d-flex justify-content-center">
    <%= link_to "編集", edit_user_registration_path, class:"btn btn-outline-primary m-3", id:"edit_user" %>
    <%= link_to "トップに戻る", root_path, class:"btn btn-outline-primary m-3" %>
  </div>
</div>